title = 'Transform functions to call on data'
status = 'Open'
id = 'f5e8c600-303e-11ea-af28-63913999ded5'
assignees = []
description = '''
We need to pass data through functions to allow it to be transformed before leaving the server.
'''
version = 'V1'

[comments]
